const bulkGroup = [
  {
    title: "Featured",
    items: [
      "com",
      "info",
      "life",
      "live",
      "me",
      "news",
      "io",
      "email",
      "world",
      "forsale",
      "domains",
      "dev",
      "site",
      "xyz",
      "vip",
      "tech",
      "app",
      "rocks",
      "shop",
      "media",
      "games",
      "tv",
    ],
  },

  {
    title: "Legacy",
    items: ["com", "net", "org", "info", "biz", "co", "co.com"],
  },

  {
    title: "Help/How-To",
    items: [
      "community",
      "education",
      "expert",
      "guide",
      "guru",
      "help",
      "how",
      "life",
      "ninja",
      "reviews",
      "social",
      "support",
      "tips",
      "tools",
      "training",
      "video",
      "wiki",
      "chat",
    ],
  },

  {
    title: "Interests",
    items: [
      "bike",
      "cricket",
      "diet",
      "fish",
      "fishing",
      "fit",
      "fitness",
      "football",
      "futbol",
      "horse",
      "surf",
      "tennis",
      "yoga",
      "coach",
      "golf",
      "training",
      "ski",
      "band",
      "dance",
      "design",
      "fashion",
      "gallery",
      "hiphop",
      "rocks",
      "photography",
      "photos",
      "pics",
      "pictures",
      "style",
      "tattoo",
      "chat",
      "domains",
      "technology",
      "science",
      "space",
    ],
  },

  {
    title: "Business",
    items: [
      "associates",
      "business",
      "capital",
      "ceo",
      "company",
      "consulting",
      "direct",
      "enterprises",
      "exchange",
      "expert",
      "financial",
      "foundation",
      "global",
      "holdings",
      "industries",
      "institute",
      "international",
      "investments",
      "limited",
      "management",
      "market",
      "network",
      "partners",
      "services",
      "solutions",
      "training",
      "ventures",
      "works",
      "world",
    ],
  },

  {
    title: "Social",
    items: [
      "buzz",
      "chat",
      "city",
      "club",
      "community",
      "dating",
      "events",
      "lgbt",
      "network",
      "party",
      "pub",
      "rocks",
      "singles",
      "social",
      "video",
      "click",
      "cool",
      "fail",
      "ninja",
      "wtf",
      "lol",
    ],
  },

  {
    title: "ccTLDs",
    items: [
      "ac",
      "ag",
      "am",
      "at",
      "be",
      "bz",
      "ca",
      "cc",
      "ch",
      "cm",
      "co",
      "co.uk",
      "cz",
      "de",
      "dk",
      "eu",
      "fm",
      "fr",
      "gs",
      "gy",
      "hn",
      "im",
      "la",
      "li",
      "lo",
      "me",
      "mn",
      "mx",
      "nl",
      "pm",
      "re",
      "sc",
      "se",
      "sh",
      "so",
      "tf",
      "tl",
      "tv",
      "tw",
      "us",
      "vc",
      "wf",
      "ws",
      "yt",
    ],
  },

  {
    title: "Professional",
    items: [
      "dental",
      "dentist",
      "healthcare",
      "surgery",
      "vet",
      "airforce",
      "army",
      "navy",
      "attorney",
      "lawyer",
      "legal",
      "engineer",
      "catering",
      "cleaning",
      "construction",
      "consulting",
      "cooking",
      "delivery",
      "design",
      "engineering",
      "hosting",
      "lighting",
      "plumbing",
      "degree",
      "education",
      "institute",
      "school",
      "training",
      "university",
    ],
  },

  {
    title: "Real Estate",
    items: [
      "agency",
      "apartments",
      "builders",
      "condos",
      "construction",
      "contractors",
      "estate",
      "forsale",
      "house",
      "land",
      "lease",
      "loans",
      "mortgage",
      "properties",
      "property",
      "rentals",
      "sale",
      "villas",
      "accountants",
      "bid",
      "capital",
      "cash",
      "credit",
      "creditcard",
      "finance",
      "financial",
      "fund",
      "gold",
      "holdings",
      "insure",
      "investments",
      "money",
      "tax",
      "trade",
    ],
  },

  {
    title: "Date Night",
    items: [
      "bar",
      "beer",
      "cooking",
      "diet",
      "fish",
      "kitchen",
      "menu",
      "pizza",
      "pub",
      "recipes",
      "restaurant",
      "reviews",
      "vodka",
      "cafe",
      "adult",
      "chat",
      "club",
      "community",
      "dating",
      "lgbt",
      "porn",
      "sexy",
      "singles",
      "social",
      "wedding",
    ],
  },
];

export default bulkGroup;
